create sequence automation.hibernate_sequence start 1 increment 1;
create table automation.application (id int8 not null, base_image varchar(200), base_image_tag varchar(200), build_tool varchar(50), context_dir varchar(200), name varchar(200), scm_ref varchar(200), scm_type varchar(200), scm_url varchar(200), primary key (id));
create table automation.build_app_command (application_id int8 not null, build_app_command varchar(255));
create table automation.build_image_command (application_id int8 not null, build_image_command varchar(255));
create table automation.cluster_labels (application_id int8 not null, label_value varchar(255), label_name varchar(255) not null, primary key (application_id, label_name));
create table automation.customer (id int8 not null, name varchar(255), primary key (id));
create table automation.customer_engagements (customer_id int8 not null, engagements_id int8 not null);
create table automation.deploy_image_command (application_id int8 not null, deploy_image_command varchar(255));
create table automation.engagement (id int8 not null, end_date bytea, name varchar(255), start_date bytea, primary key (id));
create table automation.engagement_open_shift_clusters (engagement_id int8 not null, open_shift_clusters_id int8 not null);
create table automation.engagement_team (engagement_id int8 not null, team_id int8 not null);
create table automation.env_variables (application_id int8 not null, env_value varchar(255), env_name varchar(255) not null, primary key (application_id, env_name));
create table automation.labels (application_id int8 not null, label_value varchar(255), label_name varchar(255) not null, primary key (application_id, label_name));
create table automation.open_shift_cluster (id int8 not null, image_registry varchar(255), open_shift_host_env varchar(255), user_id varchar(255), open_shift_resources_id int8, primary key (id));
create table automation.open_shift_resources (id int8 not null, primary key (id));
create table automation.open_shift_resources_projects (open_shift_resources_id int8 not null, projects_id int8 not null);
create table automation.project (id int8 not null, build_environment boolean, display_name varchar(255), name varchar(255), promotion_environment boolean, primary key (id));
create table automation.project_apps (project_id int8 not null, apps_id int8 not null);
create table automation.project_user_to_role (project_id int8 not null, user_to_role_id int8 not null);
create table automation.role (id int8 not null, name varchar(255) not null, primary key (id));
create table automation.role_mapping_roles (role_mapping_role_id int8 not null, roles_id int8 not null);
create table automation.role_mapping (id int8 not null, user_id int8, primary key (id));
create table automation.user (id int8 not null, email varchar(255) not null, first_name varchar(255), last_name varchar(255), user_name varchar(255) not null, primary key (id));
alter table automation.customer_engagements add constraint UK_61i45e6enuo1yge59kfurhdwv unique (engagements_id);
alter table automation.engagement_open_shift_clusters add constraint UK_8t6gcdvkurxc80ue5r8yec72x unique (open_shift_clusters_id);
alter table automation.open_shift_resources_projects add constraint UK_g8sri304mrqmxywoef5priux unique (projects_id);
alter table automation.project_apps add constraint UK_dvtcnumjxjf2hfsrpj35dpbq4 unique (apps_id);
alter table automation.project_user_to_role add constraint UK_clg8l5jx8lmde09n6cslmpx1c unique (user_to_role_id);
alter table automation.role_mapping_roles add constraint UK_r1bepg4uvptn27sujipx54hbj unique (roles_id);
alter table automation.build_app_command add constraint FKj7ws743dxlmvx9utmtv10o51e foreign key (application_id) references automation.application;
alter table automation.build_image_command add constraint FKk45jl5vcvc1xp3090f59vyswk foreign key (application_id) references automation.application;
alter table automation.cluster_labels add constraint FKq968gexliq9hxs97rolcfln0m foreign key (application_id) references automation.open_shift_cluster;
alter table automation.customer_engagements add constraint FK304ut8oecvyg3yoqh6felcpkr foreign key (engagements_id) references automation.engagement;
alter table automation.customer_engagements add constraint FK18d7lyuskytw8p329ag6gb9dq foreign key (customer_id) references automation.customer;
alter table automation.deploy_image_command add constraint FK14u1yndb89s5n9yulek2i4ac5 foreign key (application_id) references automation.application;
alter table automation.engagement_open_shift_clusters add constraint FKgna5nhtbtrwgpeja7u8k2bjgx foreign key (open_shift_clusters_id) references automation.open_shift_cluster;
alter table automation.engagement_open_shift_clusters add constraint FKeq9rc45ehkovnx6t98n3hs5b6 foreign key (engagement_id) references automation.engagement;
alter table automation.engagement_team add constraint FK77qifvcvtyacdaqxp99ajvq1y foreign key (team_id) references automation.user;
alter table automation.engagement_team add constraint FK2trc3728us3lorh1i1m33iwmq foreign key (engagement_id) references automation.engagement;
alter table automation.env_variables add constraint FKp1x5vcjcf7lbn6105qou8k8sk foreign key (application_id) references automation.application;
alter table automation.labels add constraint FK8g255p7a1bt8qyw10n4a0olc5 foreign key (application_id) references automation.application;
alter table automation.open_shift_cluster add constraint FKkvyx4k1lkesx3c4n49g4iqgg2 foreign key (open_shift_resources_id) references automation.open_shift_resources;
alter table automation.open_shift_resources_projects add constraint FKj6qwm90neea43sns8v5595hf foreign key (projects_id) references automation.project;
alter table automation.open_shift_resources_projects add constraint FK57ru8bc1al3lut8kvf83x31w6 foreign key (open_shift_resources_id) references automation.open_shift_resources;
alter table automation.project_apps add constraint FKjdunq5ca0q4m4k0jcv3h5h48i foreign key (apps_id) references automation.application;
alter table automation.project_apps add constraint FKrss6lcey928rjeevr7mvi0qrh foreign key (project_id) references automation.project;
alter table automation.project_user_to_role add constraint FK8mly8o8i0lvfj19vp0sl5pi5w foreign key (user_to_role_id) references automation.role_mapping;
alter table automation.project_user_to_role add constraint FK65tdd7we0f4pdl00veyaw9p0g foreign key (project_id) references automation.project;
alter table automation.role_mapping_roles add constraint FK5160c0kl5j1c2t89ogoxoqwt0 foreign key (roles_id) references automation.role;
alter table automation.role_mapping_roles add constraint FK33jyrplxs6u66g5kxxpyxhjmn foreign key (role_mapping_role_id) references automation.role_mapping;
alter table automation.role_mapping add constraint FKm7wjbg2iwhah1ml04gvbhgxfb foreign key (user_id) references automation.user;
