create sequence automation.hibernate_sequence start 1 increment 1;
create table automation.app_labels (application_id int8 not null, label_value varchar(255), label_name varchar(255) not null, primary key (application_id, label_name));
create table automation.application (id int8 not null, base_image varchar(200), base_image_tag varchar(200), build_tool varchar(50), context_dir varchar(200), name varchar(200), scm_ref varchar(200), scm_type varchar(200), scm_url varchar(200), primary key (id));
create table automation.application_pvc_associations (application_id int8 not null, pvc_associations_id int8 not null);
create table automation.application_routes (application_id int8 not null, routes_id int8 not null);
create table automation.build_app_command (application_id int8 not null, build_app_command varchar(255));
create table automation.build_image_command (application_id int8 not null, build_image_command varchar(255));
create table automation.claim_type (id int8 not null, kind varchar(255), name varchar(255), primary key (id));
create table automation.cluster_labels (application_id int8 not null, label_value varchar(255), label_name varchar(255) not null, primary key (application_id, label_name));
create table automation.customer (id int8 not null, name varchar(255), primary key (id));
create table automation.customer_engagements (customer_id int8 not null, engagements_id int8 not null);
create table automation.deploy_image_command (application_id int8 not null, deploy_image_command varchar(255));
create table automation.engagement (id int8 not null, end_date bytea, name varchar(255), start_date bytea, primary key (id));
create table automation.engagement_openshift_clusters (engagement_id int8 not null, openshift_clusters_id int8 not null);
create table automation.engagement_team (engagement_id int8 not null, team_id int8 not null);
create table automation.env_variables (application_id int8 not null, env_value varchar(255), env_name varchar(255) not null, primary key (application_id, env_name));
create table automation.group (id int8 not null, name varchar(255) not null, primary key (id));
create table automation.group_role_mapping_roles (group_role_mapping_role_id int8 not null, roles_id int8 not null);
create table automation.group_role_mapping (id int8 not null, group_id int8, primary key (id));
create table automation.label_selector (id int8 not null, primary key (id));
create table automation.match_labels (application_id int8 not null, match_label_value varchar(255), match_label_name varchar(255) not null, primary key (application_id, match_label_name));
create table automation.open_shift_cluster (id int8 not null, image_registry varchar(255), openshift_host_env varchar(255), openshift_resources_id int8, primary key (id));
create table automation.open_shift_cluster_persistent_volumes (open_shift_cluster_id int8 not null, persistent_volumes_id int8 not null);
create table automation.open_shift_resources (id int8 not null, primary key (id));
create table automation.open_shift_resources_projects (open_shift_resources_id int8 not null, projects_id int8 not null);
create table automation.persistent_volume (id int8 not null, capacity int8, name varchar(255), nfs_path varchar(255), nfs_server varchar(255), reclaim_policy varchar(255), primary key (id));
create table automation.persistent_volume_claim (id int8 not null, name varchar(255), storage int8, selector_id int8, primary key (id));
create table automation.port (id int8 not null, port int4, protocol varchar(255), target_port int4, primary key (id));
create table automation.project (id int8 not null, display_name varchar(255), environment_type varchar(255), name varchar(255), primary key (id));
create table automation.project_apps (project_id int8 not null, apps_id int8 not null);
create table automation.project_group_to_role (project_id int8 not null, group_to_role_id int8 not null);
create table automation.project_persistent_volume_claims (project_id int8 not null, persistent_volume_claims_id int8 not null);
create table automation.project_user_to_role (project_id int8 not null, user_to_role_id int8 not null);
create table automation.pv_access_mode (pv_id int8 not null, access_modes int4);
create table automation.pvc_access_mode (pvc_id int8 not null, access_modes int4);
create table automation.pvc_labels (pvc_id int8 not null, label_value varchar(255), label_name varchar(255) not null, primary key (pvc_id, label_name));
create table automation.pvcassociation (id int8 not null, mount_path varchar(255), name varchar(255), claim_type_id int8, primary key (id));
create table automation.role (id int8 not null, name varchar(255) not null, primary key (id));
create table automation.role_mapping_roles (role_mapping_role_id int8 not null, roles_id int8 not null);
create table automation.role_mapping (id int8 not null, user_id int8, primary key (id));
create table automation.route (route_type_id varchar(31) not null, id int8 not null, hostname varchar(255), name varchar(255), port int4, route_type int4, ca_cert varchar(255), cert varchar(255), insecure_policy varchar(255), key varchar(255), path varchar(255), dest_ca_cert varchar(255), route_id int8, primary key (id));
create table automation.service (id int8 not null, name varchar(255), primary key (id));
create table automation.service_ports (service_id int8 not null, ports_id int8 not null);
create table automation.user (id int8 not null, email varchar(255), first_name varchar(255), last_name varchar(255), user_name varchar(255) not null, primary key (id));
alter table automation.application_pvc_associations add constraint UK_7wc6b3g3gxvr5no4po51c542a unique (pvc_associations_id);
alter table automation.application_routes add constraint UK_3ot55kimnmxga6rtsljxw4ig3 unique (routes_id);
alter table automation.customer_engagements add constraint UK_61i45e6enuo1yge59kfurhdwv unique (engagements_id);
alter table automation.engagement_openshift_clusters add constraint UK_djnqqdayqm6b77ebv8elswav3 unique (openshift_clusters_id);
alter table automation.group_role_mapping_roles add constraint UK_hsv19fbb7gvc7s88qcrb9bpxy unique (roles_id);
alter table automation.open_shift_cluster_persistent_volumes add constraint UK_b2m0ehpipcbhx677a10gfmouu unique (persistent_volumes_id);
alter table automation.open_shift_resources_projects add constraint UK_g8sri304mrqmxywoef5priux unique (projects_id);
alter table automation.project_apps add constraint UK_dvtcnumjxjf2hfsrpj35dpbq4 unique (apps_id);
alter table automation.project_group_to_role add constraint UK_ot9ur7fuan0wxktn1qyt63npf unique (group_to_role_id);
alter table automation.project_persistent_volume_claims add constraint UK_ho4a0smsa5s1fag80gmihoe49 unique (persistent_volume_claims_id);
alter table automation.project_user_to_role add constraint UK_clg8l5jx8lmde09n6cslmpx1c unique (user_to_role_id);
alter table automation.role_mapping_roles add constraint UK_r1bepg4uvptn27sujipx54hbj unique (role_mapping_role_id, roles_id);
alter table automation.service_ports add constraint UK_2wan0i2o839bp66a2ql8nqbik unique (ports_id);
alter table automation.app_labels add constraint FKd7i5itpg8n7m0pxcwty99xect foreign key (application_id) references automation.application;
alter table automation.application_pvc_associations add constraint FKouxqhvuoxnwk3fvs1n00lw0yt foreign key (pvc_associations_id) references automation.pvcassociation;
alter table automation.application_pvc_associations add constraint FK2a26kkg3dhdh47006go8nklfy foreign key (application_id) references automation.application;
alter table automation.application_routes add constraint FKrayvtwsvik7q6owh11cnd6r9y foreign key (routes_id) references automation.route;
alter table automation.application_routes add constraint FKeg3gmeb4kj5p3nmwb4nkkgvkc foreign key (application_id) references automation.application;
alter table automation.build_app_command add constraint FKj7ws743dxlmvx9utmtv10o51e foreign key (application_id) references automation.application;
alter table automation.build_image_command add constraint FKk45jl5vcvc1xp3090f59vyswk foreign key (application_id) references automation.application;
alter table automation.cluster_labels add constraint FKq968gexliq9hxs97rolcfln0m foreign key (application_id) references automation.open_shift_cluster;
alter table automation.customer_engagements add constraint FK304ut8oecvyg3yoqh6felcpkr foreign key (engagements_id) references automation.engagement;
alter table automation.customer_engagements add constraint FK18d7lyuskytw8p329ag6gb9dq foreign key (customer_id) references automation.customer;
alter table automation.deploy_image_command add constraint FK14u1yndb89s5n9yulek2i4ac5 foreign key (application_id) references automation.application;
alter table automation.engagement_openshift_clusters add constraint FKiq6nj1iv59q3qbetjejickeb4 foreign key (openshift_clusters_id) references automation.open_shift_cluster;
alter table automation.engagement_openshift_clusters add constraint FK4pmje4vsdt2upciamfebwgu5x foreign key (engagement_id) references automation.engagement;
alter table automation.engagement_team add constraint FK77qifvcvtyacdaqxp99ajvq1y foreign key (team_id) references automation.user;
alter table automation.engagement_team add constraint FK2trc3728us3lorh1i1m33iwmq foreign key (engagement_id) references automation.engagement;
alter table automation.env_variables add constraint FKp1x5vcjcf7lbn6105qou8k8sk foreign key (application_id) references automation.application;
alter table automation.group_role_mapping_roles add constraint FKfh9drity6t5vgjwovyqk6kn16 foreign key (roles_id) references automation.role;
alter table automation.group_role_mapping_roles add constraint FK39nho75i90p4ln7vyiv6yfym9 foreign key (group_role_mapping_role_id) references automation.group_role_mapping;
alter table automation.group_role_mapping add constraint FKjsijhjtlhrfivqk34ri2itjmh foreign key (group_id) references automation.group;
alter table automation.match_labels add constraint FK4wv24pu8u3adqst7v55wpkuxf foreign key (application_id) references automation.label_selector;
alter table automation.open_shift_cluster add constraint FK2921wrg6wolgkd5lmedvnkcni foreign key (openshift_resources_id) references automation.open_shift_resources;
alter table automation.open_shift_cluster_persistent_volumes add constraint FKi1giketoh9rdwe1uq9t5c43mx foreign key (persistent_volumes_id) references automation.persistent_volume;
alter table automation.open_shift_cluster_persistent_volumes add constraint FKopg2ru2qbkms0rhjsc27ufh5w foreign key (open_shift_cluster_id) references automation.open_shift_cluster;
alter table automation.open_shift_resources_projects add constraint FKj6qwm90neea43sns8v5595hf foreign key (projects_id) references automation.project;
alter table automation.open_shift_resources_projects add constraint FK57ru8bc1al3lut8kvf83x31w6 foreign key (open_shift_resources_id) references automation.open_shift_resources;
alter table automation.persistent_volume_claim add constraint FKbhst666800dxdoyt6weja2nli foreign key (selector_id) references automation.label_selector;
alter table automation.project_apps add constraint FKjdunq5ca0q4m4k0jcv3h5h48i foreign key (apps_id) references automation.application;
alter table automation.project_apps add constraint FKrss6lcey928rjeevr7mvi0qrh foreign key (project_id) references automation.project;
alter table automation.project_group_to_role add constraint FKt0b8wjox0ko4ewkbda5oj1kqh foreign key (group_to_role_id) references automation.group_role_mapping;
alter table automation.project_group_to_role add constraint FKmqh8a09goiwvw8djowf4f9yfk foreign key (project_id) references automation.project;
alter table automation.project_persistent_volume_claims add constraint FKaw3a273cahjom9n1rn1mork1d foreign key (persistent_volume_claims_id) references automation.persistent_volume_claim;
alter table automation.project_persistent_volume_claims add constraint FKqiytsnuktyop39y6weqf5vrl0 foreign key (project_id) references automation.project;
alter table automation.project_user_to_role add constraint FK8mly8o8i0lvfj19vp0sl5pi5w foreign key (user_to_role_id) references automation.role_mapping;
alter table automation.project_user_to_role add constraint FK65tdd7we0f4pdl00veyaw9p0g foreign key (project_id) references automation.project;
alter table automation.pv_access_mode add constraint FKkgh5rol861ja67stt2rujuhat foreign key (pv_id) references automation.persistent_volume;
alter table automation.pvc_access_mode add constraint FK128lmbj29tjj4e6ih1qmrhoc9 foreign key (pvc_id) references automation.persistent_volume_claim;
alter table automation.pvc_labels add constraint FK7vtwyfwl1qfl6g96rbd01hp1e foreign key (pvc_id) references automation.persistent_volume;
alter table automation.pvcassociation add constraint FKp6mjubycc5mmv93dbb33ykt1o foreign key (claim_type_id) references automation.claim_type;
alter table automation.role_mapping_roles add constraint FK5160c0kl5j1c2t89ogoxoqwt0 foreign key (roles_id) references automation.role;
alter table automation.role_mapping_roles add constraint FK33jyrplxs6u66g5kxxpyxhjmn foreign key (role_mapping_role_id) references automation.role_mapping;
alter table automation.role_mapping add constraint FKm7wjbg2iwhah1ml04gvbhgxfb foreign key (user_id) references automation.user;
alter table automation.route add constraint FKil496t589ha08a5ukwp215abk foreign key (route_id) references automation.service;
alter table automation.service_ports add constraint FKbh5jxmoyk7cys2yggttqemej1 foreign key (ports_id) references automation.port;
alter table automation.service_ports add constraint FK9vdwe19i9okgj9crciem2q89d foreign key (service_id) references automation.service;
